version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/docusaurus-graphql-plugin"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
